

namespace api.artpixxel.data.Models
{
    public enum RegularTemplate
    {
        Setof3Set1 = 0,
        Setof3Set2 = 1,
        Setof3Set3 = 2,
        Setof4Set1 = 3,
        Setof6Set1 = 4,
        Setof9Set1 = 5,
        Setof4Set2 = 6,
        Setof4Set3 = 7,
        Setof4Set4 = 8,
        Setof4Set5 = 9,
        Setof6Set2 = 10,
        Setof6Set3 = 11,
        Setof9Set2 = 12,
        Setof9Set3 = 13,
        Setof9Set4 = 14,
        Setof5Set1= 15,
        Setof6Set4 = 16,
        Setof6Set5 = 17,
        Setof4Set6 = 18,
        Setof4Set7 = 19,
        Setof4Set8 = 20,
        Setof6Set6 = 21,
        Setof9Set5 = 22,
        Setof6Set7 = 23,
        Setof6Set8 = 24,
        Setof6Set9 = 25,
        Setof6Set10 = 26,
        Setof6Set11 = 27,
        Setof6Set12 = 28,
        Setof6Set13 = 29,
        Setof6Set14 = 30,
        Setof6Set15 = 31,
        Setof6Set16 = 32,
        Setof3Set4 = 33,
        Setof3Set5 = 34,
        Setof3Set6 = 35,
        Setof3Set7 = 36,
        Setof4Set9 = 37,
        Setof4Set10 = 38,
        Setof4Set11 = 39,
        Setof5Set2 = 40,
        Setof7Set1 = 41,
        Setof8Set1 = 42,
        Setof8Set2 = 43,
        Setof8Set3 = 44,
        Setof9Set6 = 45,
        Setof9Set7 = 46,
        Setof9Set8 = 47,
        Setof9Set9 = 48,
        Setof9Set10 = 49,
        Setof9Set11 = 50,
        Setof9Set12 = 51,
        Setof9Set13 = 52,
        Setof12Set1 = 53,
        Setof12Set2 = 54,
        Setof15Set1 = 55,

    }



    public static class RegularTemplateExtension
    {
        public static string ParsedName(this RegularTemplate template)
        {
            
           string parsedTemplate = template switch
            {
                RegularTemplate.Setof3Set1 => "Set of 3 (Set 1)",
                RegularTemplate.Setof3Set2 => "Set of 3 (Set 2)",
                RegularTemplate.Setof3Set3 => "Set of 3 (Set 3)",
                RegularTemplate.Setof4Set1 => "Set of 4 (Set 1)",
                RegularTemplate.Setof4Set2 => "Set of 4 (Set 2)",
                RegularTemplate.Setof4Set3 => "Set of 4 (Set 3)",
                RegularTemplate.Setof4Set4 => "Set of 4 (Set 4)",
                RegularTemplate.Setof4Set5 => "Set of 4 (Set 5)",
                RegularTemplate.Setof4Set6 => "Set of 4 (Set 6)",
                RegularTemplate.Setof4Set7 => "Set of 4 (Set 7)",
                RegularTemplate.Setof4Set8 => "Set of 4 (Set 8)",
                RegularTemplate.Setof5Set1 => "Set of 5 (Set 1)",
                RegularTemplate.Setof6Set1 => "Set of 6 (Set 1)",
                RegularTemplate.Setof6Set2 => "Set of 6 (Set 2)",
                RegularTemplate.Setof6Set3 => "Set of 6 (Set 3)",
                RegularTemplate.Setof6Set4 => "Set of 6 (Set 4)",
                RegularTemplate.Setof6Set5 => "Set of 6 (Set 5)",
                RegularTemplate.Setof6Set6 => "Set of 6 (Set 6)",
                RegularTemplate.Setof6Set7 => "Set of 6 (Set 7)",
                RegularTemplate.Setof6Set8 => "Set of 6 (Set 8)",
                RegularTemplate.Setof6Set9 => "Set of 6 (Set 9)",
                RegularTemplate.Setof6Set10 => "Set of 6 (Set 10)",
                RegularTemplate.Setof6Set11 => "Set of 6 (Set 11)",
                RegularTemplate.Setof6Set12 => "Set of 6 (Set 12)",
                RegularTemplate.Setof6Set13 => "Set of 6 (Set 13)",
                RegularTemplate.Setof6Set14 => "Set of 6 (Set 14)",
                RegularTemplate.Setof6Set15 => "Set of 6 (Set 15)",
                RegularTemplate.Setof6Set16 => "Set of 6 (Set 16)",
                RegularTemplate.Setof3Set4 => "Set of 3 (Set 4)",
                RegularTemplate.Setof3Set5 => "Set of 3 (Set 5)",
                RegularTemplate.Setof3Set6 => "Set of 3 (Set 6)",
                RegularTemplate.Setof3Set7 => "Set of 3 (Set 7)",
                RegularTemplate.Setof4Set9 => "Set of 4 (Set 9)",
                RegularTemplate.Setof4Set10 => "Set of 4 (Set 10)",
                RegularTemplate.Setof4Set11 => "Set of 4 (Set 11)",
                RegularTemplate.Setof5Set2 => "Set of 5 (Set 2)",
                RegularTemplate.Setof7Set1 => "Set of 7 (Set 1)",
                RegularTemplate.Setof8Set1 => "Set of 8 (Set 1)",
                RegularTemplate.Setof8Set2 => "Set of 8 (Set 2)",
                RegularTemplate.Setof8Set3 => "Set of 8 (Set 3)",
                RegularTemplate.Setof9Set1 => "Set of 9 (Set 1)",
                RegularTemplate.Setof9Set2 => "Set of 9 (Set 2)",
                RegularTemplate.Setof9Set3 => "Set of 9 (Set 3)",
                RegularTemplate.Setof9Set4 => "Set of 9 (Set 4)",
                RegularTemplate.Setof9Set5 => "Set of 9 (Set 5)",
                RegularTemplate.Setof9Set6 => "Set of 9 (Set 6)",
                RegularTemplate.Setof9Set7 => "Set of 9 (Set 7)",
                RegularTemplate.Setof9Set8 => "Set of 9 (Set 8)",
                RegularTemplate.Setof9Set9 => "Set of 9 (Set 9)",
                RegularTemplate.Setof9Set10 => "Set of 9 (Set 10)",
                RegularTemplate.Setof9Set11 => "Set of 9 (Set 11)",
                RegularTemplate.Setof9Set12 => "Set of 9 (Set 12)",
                RegularTemplate.Setof9Set13 => "Set of 9 (Set 13)",
                RegularTemplate.Setof12Set1 => "Set of 12 (Set 1)",
                RegularTemplate.Setof12Set2 => "Set of 12 (Set 2)",
                RegularTemplate.Setof15Set1 => "Set of 15 (Set 1)",
                _ => "Set of 9 (Set 1)",
            };
            return parsedTemplate;
        }
    }
}
